apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lofi-certificate
spec:
  commonName: lofi.ediri.online
  dnsNames:
    - lofi.ediri.online
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: lofi-tls