apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lofi

images:
  - name: lofi
    newName: ghcr.io/dirien/lofi-app
    newTag: latest

resources:
  - deployment.yaml
  - ingress.yaml
  - certifiacte.yaml
  - svc.yaml
  - github-docker-secret-ss.yaml