apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lofi-app
  namespace: argo
spec:
  destination:
    namespace: lofi
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application/deployment
    repoURL: https://github.com/dirien/digitalocean-kubernetes-challenge.git
    targetRevision: main
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true