apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-argocd-example-build-deploy-pipeline
spec:
  workspaces:
    - name: source-dir
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/dirien/digitalocean-kubernetes-challenge.git'
        - name: revision
          value: cicd
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-argocd-example-build-deploy-pipeline-run
spec:
  pipelineRef:
    name: tekton-argocd-example-build-deploy-pipeline
  workspaces:
    - name: source-dir
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
          accessModes:
            - ReadWriteOnce
