apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-argocd-example-build-deploy-pipeline
spec:
  workspaces:
    - name: source-dir
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/dirien/digitalocean-kubernetes-challenge.git'
        - name: revision
          value: cicd
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.5
      workspaces:
        - name: source
          workspace: source-dir
    - name: golangci-lint
      params:
        - name: package
          value: github.com/dirien/simple
        - name: context
          value: application/lofi-app
      taskRef:
        name: golangci-lint
        bundle: gcr.io/tekton-releases/catalog/upstream/golangci-lint:0.2
      workspaces:
        - name: output
          workspace: source-dir

