apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lofi-pipeline
spec:
  workspaces:
    - name: source-dir
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/dirien/digitalocean-kubernetes-challenge.git'
        - name: revision
          value: cicd
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.5
      workspaces:
        - name: output
          workspace: source-dir
    - name: golangci-lint
      params:
        - name: package
          value: github.com/dirien/simple
        - name: context
          value: application/lofi-app
      taskRef:
        name: golangci-lint
        bundle: gcr.io/tekton-releases/catalog/upstream/golangci-lint:0.2
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source-dir
    - name: golang-build
      params:
        - name: package
          value: github.com/dirien/simple
        - name: packages
          value: ./application/lofi-app
      taskRef:
        name: golang-build
        bundle: gcr.io/tekton-releases/catalog/upstream/golang-build:0.3
      runAfter:
        - golangci-lint
      workspaces:
        - name: source
          workspace: source-dir

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: lofi-pipeline-run
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  pipelineRef:
    name: lofi-pipeline
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/os: linux
      doks.digitalocean.com/node-pool: tools-node-pool
    tolerations:
      - effect: NoSchedule
        key: tools
        operator: Equal
        value: "true"
  workspaces:
    - name: source-dir
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
          accessModes:
            - ReadWriteOnce
