apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-argocd-example-build-deploy-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/dirien/digitalocean-kubernetes-challenge.git'
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir

