config:
  auth0:clientId:
    secure: AAABAKR4otR3K7wuLJaOmlKAwbLAwPvhi16zQLA14/tY4RBCa5dmntXeL/DN+xle/MnM5jdYTWUi/mWQKLqFfA==
  auth0:clientSecret:
    secure: AAABAIPJ7yfY17esHsm6tOh1ODYGYFd1IQmqkr3/KsmPt6Faa8ET3Achojatk2Kvje3X0YSDIQkmcMi43NGyDjtceCM5197r+BZsNa6EKa/4rJ9ptk35v9WIU3Tf4bEO
  auth0:domain: ediri.eu.auth0.com
