apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: kaniko-github-configjson
spec:
  encryptedData:
    .dockerconfigjson: AgCbz1zIMJaDnABlECJ3sLLJ0rQIXHUZWUj0ELmCILgnHGmSDQ8+4Y6FaFeNrj/qzXFoCMf/GTdyYRvw+YedMS6GE88j4RZC5BP8zkxY2HaWWt70n6SBXCMMc1JHxoVX331w1KRqatuN2bxUNVlrBVjh7n2xY7ZScYNb7hxF1b/zhKpHo7OChTSlu9cyfUjl6IZUOv7Yq5EdOPxI1hIk2v9OPJ8Snr6POSklZfDNU2NFGw1ucbhgeOnkVXNOyeUXMGKBy0qMaoyse+/i8fr5iYIpwcpTTvV1TmMfzN2uwMB/qMYNLffsd/u3HUWHI+BBC/yNZOsO46hdWeNMRV/yX0w73lkPk38PFJ3ZsPkntOYqy15lujgcU9KFQ0/a+TAEE15KdiC6KKI9m5Tcj67lllE0COqfblK8VYrAh2Y79hyq2KjdKCRpiDgp2EuHVagzSSuymueAAlOklgMN3hplHAhY+ZuzPmbf2T9T1FEOrMD9E/r/ClzibvyriETNJ1b+0wuRIX25DQm+CundzzfAH/208/wBWbGl5unXcFNIGEJqy7aOOgQqDwLWlX07zAzpRpvA4TjPYmdmY7XwdvabOaIprObG1SOInQuoc1DcEykP3ZR7l3DoBo5YOtCws740ZxymI4iEvLKx8gqJAtolvulElBBlK6qzJvCqUCsimcvT84M9Z7wMftnfkocElSuVOBSzUnbao5E0a9ow9MNmLsUZDxPoVYwYB754IXS9bDcizhPSszEcyAIhO2KCNGL+6NQizoVNZGFhxRA50wVWAvmU4idANuZ6GWNzUTlsBpjhycO8kM/HNlCvMHBvc/ULdz+BK8IcpggZriK2p0JsCsMwJwFumKtn0lXVblai
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: kaniko-github-configjson
    type: kubernetes.io/dockerconfigjson

