kind: Secret
apiVersion: v1
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "changemewithasecret"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-github-container-user-pass
  annotations:
    tekton.dev/docker-0: https://ghcr.io
type: kubernetes.io/basic-auth
stringData:
  username: "<cleartext username>"
  password: "<cleartext password>"