apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-directory
spec:
  workspaces:
    - name: source
  steps:
    - name: list
      image: alpine:latest
      workingDir: $(workspaces.source.path)
      script: |
        ls -la