apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: [ "pull_request","push" ]
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: lofi-trigger-sa
            nodeSelector:
              beta.kubernetes.io/os: linux
              doks.digitalocean.com/node-pool: tools-node-pool
            tolerations:
              - effect: NoSchedule
                key: tools
                operator: Equal
                value: "true"
